server:
  port: 8081  # Asegúrate de que tiene un puerto diferente

spring:
  application:
    kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: mi-grupo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  r2dbc:
    url: r2dbc:postgresql://ep-dry-feather-a50464ji.us-east-2.aws.neon.tech:5432/jose?options=endpoint%3Dep-dry-feather-a50464ji&sslmode=require
    username: JG-ChatBot_owner
    password: Qbr4YsUfdz6R
