server:
  port: 8080

spring:
  kafka:
  producer:
    bootstrap-servers: kafka:9092
  r2dbc:
    url: r2dbc:postgresql://ep-dry-feather-a50464ji.us-east-2.aws.neon.tech:5432/jose?options=endpoint%3Dep-dry-feather-a50464ji&sslmode=require
    username: JG-ChatBot_owner
    password: Qbr4YsUfdz6R
